### ISSUE TITLE
Example of currying identifying information

### ISSUE THREAD

**Issue by AndrewSB** [willowtreeapps/cordux#13]
Loving the work thats gone into this library!

Having a little trouble wrapping my head around this concept:
<img width="939" alt="screen shot 2016-08-31 at 11 48 29 am" src="https://cloud.githubusercontent.com/assets/3814772/18142116/fd63cfe8-6f70-11e6-86b2-7a27df86b6a8.png">

Is there a more fleshed out example that I can look at?

**Comment by ianterrell** [comment]
Unfortunately there is not yet a more fleshed out example to look at, and I struggle to find a clearer way of expressing the idea. :)

The basic idea is this:
1. State may hold multiple instances of a single type. Consider an app like IMDB, in which state may hold information about many movies.
2. You may want to have multiple controllers showing different instances of the same data type at the same time. Consider our movie app has a tabbed navigation, and one tab shows this week's newest movie while another tab shows the most popular movie of all time.
3. _Something_ has to be able to tie a specific movie to a specific controller.
4. "Normally" that would be controller (i.e. `let vc = MovieController(movieID: "Batman")`). However, I want to make controllers dumber, so something else has to do it.

A curried subscription transformation is my solution to 3's "_Something_". The transform function is holding the identifying information so that the controller does not need to know how to extract the information for its specific movie.

If I create an example in this project that uses this technique I'll let you know.

**Comment by AndrewSB** [comment]
@ianterrell I'm trying to implement this for an app I'm working on, and I'm having some trouble.

I may be going about it the wrong way, but I'm running into a problem when I create multiple instances of a ChallengeController, which can dispatch actions like `updateOrdering`, and `updateSource`. This works fine when there's just one ChallengeController around to react to those actions, but when there are multiple reducers listening for those actions, things break.

My state looks like
- AppState
  - FeedState (represents a tabBar view)
    - ChallengeState
  - FriendsState (represents another tabBar view)
     - ChallengeState
  
Concretely, if I dispatch an action meant for the FeedState's ChallengeState, it affects the FriendsState's ChallengeState as well.
I have a feeling I need to curry some identifying information in the actions, but I'm not sure how to accomplish that, I have a feeling it has something to do with my misunderstanding above. 

I'd love to better understand how you guys solved this problem so I can do the same thing!
The app is open source, here's the [AppState](https://github.com/AndrewSB/wrytr/blob/master/wrytr/AppState.swift)

**Comment by ianterrell** [comment]
Hi @AndrewSB,

I wouldn't necessarily call it currying here, but you do need to include some identifying information in your action.

Consider

```swift
enum ChallengeIndex {
    case feed
    case friend
}

enum ChallengeAction {
    case updateOrdering(index: ChallengeIndex, Data)
    case updateSource(index: ChallengeIndex, Source)
}
```

And then in your reducer you can switch on the `index` to know which specific `ChallengeState` to update. 

If you're reusing a coordinator for that, consider baking that information in. 

```swift
class ChallengeCoordinator: Coordinator {
    let index: ChallengeIndex
    init(index: ChallengeIndex) {
        self.index = index
    }
}

extension ChallengeCoordinator: ChallengeViewControllerHandler {
    func updateSource(source: Source) {
        store.dispatch(ChallengeAction.updateSource(index: index, source)
    }
}
```

That's fundamentally what we're doing in our apps, along with being sure to pull out the right substate per coordinator.

Let me know if this doesn't help.

**Comment by mattyohe** [comment]
Thanks for continuing to check this out, @AndrewSB 

 If you noticed in release v0.1.11 of Cordux some new ViewControllerLifecycle methods were added: https://github.com/willowtreeapps/cordux/commit/8a7115a8eae1a95b0eea38531899d683592876fa

This will allow you to unsubscribe any view controllers that are not on screen (as is the case here when you switch between tabs). This is achieved by calling `unsubscribe(_:)` in the viewDidDissappear method as is seen here (albeit in a viewDidLoad, and subscribing instead of unsubscribing) https://github.com/willowtreeapps/cordux/blob/21e7bc25627715373456fdf0841ab02e6243b2d1/Example/CorduxPrototype/AuthenticationCoordinator.swift#L66

Looks like @ianterrell just responded with an answer that takes it in a different direction. Hopefully one of these works for you.

**Comment by AndrewSB** [comment]
@ianterrell thank you for the help, that makes sense!

@mattyohe: your solution is simpler, but I'm not sure if it would work for me. My view controller's reducers are long living (see [AppState](https://github.com/AndrewSB/wrytr/blob/master/wrytr/AppState.swift)), so even if I unsubscribe the view controllers, both my `friendsReducer` and `feedReducer` would still be listening and mutate the `feedState` and `friendState` regardless of what's on screen.
Does that seem like an anti pattern to you? Should I instead be subscribing and unsubscribing my view model reducers based on what's visible on screen? (currently just doing [this](https://github.com/AndrewSB/wrytr/blob/master/wrytr/AppState.swift#L36))

**Comment by mattyohe** [comment]
> My view controller's reducers are long living

As expected.

> Does that seem like an anti pattern to you? Should I instead be subscribing and unsubscribing my view model reducers based on what's visible on screen?

You should not be unsubscribing reducers, only view controllers. Sorry to lead you astray. @ianterrell's solution is the correct one here.
